### ISSUE TITLE
compile error

### ISSUE THREAD

**Issue by sunkechenjing** [PocketSprite/8bkc-chooser#1]
When i compile chooser , An error occurred.I had copied "libesphttpd" into component,but compiling was error.How to solve the problem?Thanks!

 /home/sun/esp/esp-idf/make/component_common.mk:1: Deprecated feature: No longer necessary to include component_common.mk from /home/sun/esp/8bkc-chooser/main/component.mk
CC build/main/cgi.o
/home/sun/esp/8bkc-chooser/main/./cgi.c:4:21: fatal error: esp8266.h: No such file or directory
compilation terminated.
/home/sun/esp/esp-idf/make/component_wrapper.mk:273: recipe for target 'cgi.o' failed
make[1]: *** [cgi.o] Error 1
/home/sun/esp/esp-idf/make/project.mk:450: recipe for target 'component-main-build' failed

**Comment by Spritetm** [comment]
Libesphttpd actually is a submodule; I just noticed it's still pointing to my own internal server, however. Will change this as soon as I have time.

**Comment by Spritetm** [comment]
Should be changed to a local repo now.
