### ISSUE TITLE
chooser running error

### ISSUE THREAD

**Issue by sunkechenjing** [PocketSprite/8bkc-chooser#2]
There is some info on screen.
WIFI AP DKSDR
GO TO:
HTTP://192.168.4.1/
what's next step?Thanks

**Comment by Spritetm** [comment]
Press a key to get to the menu?

**Comment by sunkechenjing** [comment]
There is no response to any key.  How do I operate？

**Comment by Spritetm** [comment]
I dunno? You don't really give me much information to work with here. It would help if you'd tell me which hardware you use, if you compiled this yourself or if you're using the default PocketSprite chooser, how you compiled this if you did that, if you use a specific esp-idf version, if you run the chooser as an app or directly from the factory partition, etc.

**Comment by sunkechenjing** [comment]
Sorry.I using a esp32 module(modified to 16mB),i downloaded chooser and libesphttpd,At last,I had makeing flash chooser to esp32,then There is some info on screen.
WIFI AP DKSDR
GO TO:
HTTP://192.168.4.1/
what's next step?Thanks
There is no response to any key.

**Comment by Spritetm** [comment]
At that point, the PocketSprite acts as an access point and you can use WiFi to upload new ROMs and apps. To actually use the UI, you'd need buttons and a D-pad connected to the ESP32.

**Comment by Spritetm** [comment]
Also, I'm going to close this issue. Running the Chooser on any other hardware than the pocketsprite is not something I'm really comfortable supporting at this moment, given the fact that the first units have only just reached our customers. The source is open and documented, so with a bit of reading you should be able to make it work.

**Comment by sunkechenjing** [comment]
hi!Spritetm. I am a  high school teacher, teaching technology and computer.I find pocketsprite in here.I wish to using pocketsprite for a teaching computer program.I don't know how to buy pocketsprite.I think pocketsprite is a very good teaching tool.It contain a large teaching resource and it's fun.Can you send me buy link?

**Comment by Spritetm** [comment]
Yes, you can buy one at http://pocketsprite.com .
