### ISSUE TITLE
Cannot install

### ISSUE THREAD

**Issue by JooJooBee666** [PocketSprite/8bkc-chooser#6]
I was able to compile this after I made a few modifications to the HTML files to test and tried to upload but nothing happened.  I also compiled fluppy bird and nofrendo (after fixing a minor compile error in main.c) but when I choose the app and hit upload, the pink "load" bar just goes right to the finish.  I'm not really sure what I'm doing wrong but there appears to be an issue with chooser and uploading apps...which I don't see a way to fix if I cannot upload an app file.  ROM files upload fine.

**Comment by JooJooBee666** [comment]
Nevermind.  Apparently device was out of space.  There is just no warning.

**Comment by Spritetm** [comment]
Yep, initial firmware has that bug unfortunately. Feel free to update to https://www.reddit.com/r/PocketSprite/comments/8hec66/testers_wanted_beta_apps_round_2/ to get rid of that. (Or use the current version of the Chooser sources, it also has this issue fixed.)

**Comment by JooJooBee666** [comment]
Thanks.  Once I figured out what the issue was I was able to install the apps (including the chooser update).. I've bookedmarked the reddit link.
