### ISSUE TITLE
Compile cgi.c: esp8266.h not found

### ISSUE THREAD

**Issue by jlunz** [PocketSprite/8bkc-chooser#8]
Hi:
Just received my PocketSprite - awesome little device, thanks a lot for making it!

I'm facing one issue while trying to compile 8bkc-chooser:
`
tmp/8bkc-chooser/main/./cgi.c:4:21: fatal error: esp8266.h: No such file or directory
compilation terminated.
`
No output from a find . -iname "esp8266.h" in my working tree.

I tried on both Arch and Debian 9.
Please find the steps used to setup compile environment below:
```bash
wget https://dl.espressif.com/dl/xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
tar xf xtensa-esp32-elf-linux64-1.22.0-80-g6c4433a-5.2.0.tar.gz
export PATH="$PATH:$(pwd)/xtensa-esp32-elf/bin"
git clone --recursive https://github.com/PocketSprite/8bkc-sdk.git
export POCKETSPRITE_PATH="$(pwd)/8bkc-sdk"
git clone https://github.com/PocketSprite/8bkc-chooser
pushd 8bkc-chooser
    make
popd
```

**Comment by Spritetm** [comment]
I think you're missing a --recursive in the 8bkc-chooser `git clone` command.

**Comment by jlunz** [comment]
Oh no, sorry, did not see the very obvious. Thanks!
